[package]
name = "use-thermal-expansion"
description = "Primitive thermal-expansion helpers"
publish = true
authors.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
documentation = "https://docs.rs/use-thermal-expansion"
keywords = ["materials", "thermal", "expansion", "coefficient"]
categories = ["algorithms", "science"]

[lints]
workspace = true